### PR TITLE
use luv_set_thread_cb for better thread support

### PR DESCRIPTION
**Pull request by zhaozg**
better support luv thread module

### CODE REVIEW

**Comment by creationix** [comment]
So this changes luvi to run an instance per thread?  Does the main thread still run luvi?

**Comment by zhaozg** [comment]
yes and yes

**Comment by zhaozg** [comment]
I will give example later

**Comment by zhaozg** [comment]
hi @creationix , please see https://gist.github.com/zhaozg/8a236b81f92ea6f929fd
to run this demo, you need use luajit-nanomsg

**Comment by zhaozg** [comment]
It need do something to make child thread with luvit env,(require not work rightly with bundle path)

**Pull request merged**
