### PR TITLE
newest openssl version

### PR DESCRIPTION
**Pull request by polyswarmer**
see https://www.openssl.org/source/

### CODE REVIEW

**Comment by joerg-krause** [comment]
Why not 1.1.1?

_The latest stable version is the 1.1.1 series. This is also our Long Term Support (LTS) version, supported until 11th September 2023._

**Comment by rphillips** [comment]
We should try and bump to 1.1.1 if we can.

**Comment by polyswarmer** [comment]
Why not 1.1.1?

B/c of the KISS principle: originally I thought "better change less", since there is still half a year of support ("The 1.1.0 series is currently only receiving security fixes and will go out of support on 11th September 2019.") and until then 1.1.1 could slowly be added/tested/integrated.

But... since the general consensus seems for 1.1.1, I'll add a patch for that

**Comment by polyswarmer** [comment]
closing 

* new patch here:

https://github.com/luvit/luvi/pull/196

**Pull request closed without merging**
