### PR TITLE
update lua-openssl to tag 0.7.0

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by zhaozg** [comment]
this commit will cause luvit fail, because some api changed, I will make a PR for luvit to fit newest lua-openssl.

**Comment by creationix** [comment]
Do we also want to update openssl itself?  Probably a good time if we're doing a new luvi rebuild.

**Comment by creationix** [comment]
@zhaozg is this openssl release compatible with your library? https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_0e

**Comment by creationix** [comment]
Looks like we're currently on 1.0.2h

**Comment by creationix** [comment]
We should probably at least move to 1.0.2k to get the latest security patches in that branch. https://www.openssl.org/news/openssl-1.0.2-notes.html
@rphillips how have you been updating the luvit/openssl repo?

**Comment by zhaozg** [comment]
to @creationix 

>@zhaozg is this openssl release compatible with your library? >https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_0e

Yes, It support both 1.0.2 and 1.1.0.

**Pull request merged**
