### PR TITLE
pull request for port luvi to Lua 5.3

### LINKED ISSUE #140: Bring luvi (and luvit environments) to Lua 5.3
Hi dear @creationix,

I have done to port luvi into Lua 5.3, some modifies to:
  - lrexlib: compatible with Lua 5.3
  - lua_zlib: compatible with Lua 5.3
  - luv:
      - add lua_add_executable() to lua.cmake.
      - remove `LUA_USE_DLOPEN` when Win32.
  - add `env.os` and `env.arch` to lenv.c
  - add global `unpack` and `loadstring` to lvuibundle.lua
  - add Lua 5.3 compatible to luvi.h
  - add a compatible `bit` module to fit `lit`.

After that, lit now works with Lua 5.3 now. but luvit still doesn't work. I hope lit package manager can add depends like "lua > 5.1" or "luajit > 2.0" to enable modules for luajit or lua. So we can write plain Lua script in lit (but not luvit itself).

as there are many modifies, so I hope a guide how to make a pull request :(

regards,
Xavier Wang.

### PR DESCRIPTION
**Pull request by starwing**
this is the first version for early review, to fix #140.

second commit resolved most warnings I meet when build on windows using VS2015.

To make this, I can check modifies on other platform (I only tested on Windows)

### CODE REVIEW

**Comment by starwing** [comment]
Oops, it seems that I can not checkout a pull request branch that not merged :(

stupid mistable :(

**Comment by creationix** [comment]
Looks good, just fix the submodules.

**Comment by starwing** [comment]
@creationix so the missing submodule is luvit/openssl, I submit a pull request to avoid amount of warnings building on VS2015.

**Comment by starwing** [comment]
I have submit pull request to [openssl](https://github.com/luvit/openssl/pull/22) but it seems not reply, I will try remove openssl update (only for avoid warnings) and commit again :)

**Comment by starwing** [comment]
lua-openssl need PTHREADS to enable `CRYPTO_thread_setup`, in theory we can `add_definitions(-DPTHREADS)` directly, as in rockspecs, but lua-openssl has a bug, I have submit a pull request to up stream, but it's not affect this request (I checked about exists of pthread library)

**Comment by creationix** [comment]
How can I build luvi using lua?  I see the `WITH_LUA_ENGINE` variable, but am unsure how to pass it in.  Also we should probably have the Ci build and test both flavors.

**Comment by creationix** [comment]
If I add `-DWITH_LUA_ENGINE=Lua` to the tiny target in the Makefile, it seems to try, but fails with:

    CMake Error: CMake can not determine linker language for target: lua

**Comment by starwing** [comment]
? i use this option, let me check it

**Comment by starwing** [comment]
I have double checked, using:
cmake -DWITH_LUA_ENGINE=Lua ..

build success, but I only checked on Windows, I will check on Linux.

**Comment by starwing** [comment]
Sorry for my fall. I found a bug when build with Lua in luv, the default option to build Lua is build a amalg version (lua_one.c), but the path of file lua_one.c is wrong. I have made a [pull request](https://github.com/luvit/luv/pull/221) on up stream.

but I tested:
`cmake -DWITH_LUA_ENGINE=Lua -DWITH_AMALG=OFF ..`

it works. After merge from up stream, simply define WITH_LUA_ENGINE works.

I will make a CI pull request in time.

**Comment by creationix** [comment]
Now that luvi can have multiple lua engines, we should show the engine and version in `luvi -v` I think.

**Pull request merged**
