### PR TITLE
add lpeg into luvi(optional)

### PR DESCRIPTION
**Pull request by zhaozg**
feed self: https://github.com/luvit/luvi/issues/114

### CODE REVIEW

**Comment by creationix** [comment]
I think this is missing something.  lpeg isn't built into luajit is it?

**Comment by zhaozg** [comment]
because lpeg not have office git, so I import code into deps/lpeg, version 0.12.2

**Comment by creationix** [comment]
I created a mirror under the luvit org.  I have a policy of keeping any sizable dependencies / third-party-code in submodules so as to not distort the stats of this repo. https://github.com/luvit/lpeg

Also can you make it an optional item like the pcre/rex, openssl, and friends?

I plan on including lpeg in the "regular" build, but I want the "tiny" build to be bare.

**Comment by zhaozg** [comment]
use lpeg from git, and included in regular build but without in tiny

**Comment by creationix** [comment]
Perfect, thanks!

**Comment by creationix** [comment]
@zhaozg would you like a new luvit release soon?  I don't know if you use my prebuilt binaries or build your own from source?

**Comment by zhaozg** [comment]
I use from sourse, feel free to make release at your time line

**Comment by creationix** [comment]
Ok, thanks.

**Pull request merged**
