### PR TITLE
add holy build support

### PR DESCRIPTION
**Pull request by rphillips**
## Why

Creates a cross platform x86, x64 binary. Should be quite portable.

### CODE REVIEW

**Comment by creationix** [comment]
```
f28dbb68ea3a: Verifying Checksum
Pulling repository docker.io/phusion/holy-build-box-64
2cc490d44461: Error pulling image (latest) from docker.io/phusion/holy-build-box-64, Untar re-exec error: exit status 1: output: write /hbb_exe/lib/libcrypto.a: no space left on device xe/lib/libcrypto.a: no space left on device
56e0de455021: Download complete
Error pulling image (latest) from docker.io/phusion/holy-build-box-64, Untar re-exec error: exit status 1: output: write /hbb_exe/lib/libcrypto.a: no space left on device
make: *** [linux-build-box-regular] Error 1
```

**Comment by creationix** [comment]
This is after installing `gnu-tar`, `docker`, and `docker-machine` from homebrew.

**Comment by rphillips** [comment]
Hmm. I got a clean build again with a virtualbox docker-machine.

Using this version? docker-machine version 0.5.1 (HEAD)

**Comment by rphillips** [comment]
after looking at the log some more... looks like the docker pull errored out. maybe to a networking issue.

**Pull request merged**
