### PR TITLE
bump to openssl 1.0.2g try #2

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by creationix** [comment]
+1

**Comment by zhaozg** [comment]
good job

**Comment by rphillips** [comment]
thanks. such a pain.

**Comment by rphillips** [comment]
@zhaozg @creationix if you guys could try this branch on your various machines, I would appreciate it. Luvit tests are passing for me with it on Linux, Windows 32/64, and OSX.

**Comment by creationix** [comment]
tested on Linux x64 and Linux armv7

Also ran against luvit and lit tests, all green now.

**Pull request merged**
