### PR TITLE
R4R: add asm support

### PR DESCRIPTION
**Pull request by rphillips**
Depends on https://github.com/luvit/openssl/pull/18

- [x] OSX 64
- [x] Win32
- [x] Win64
- [x] Linux32
- [x] Linux64
- [x] LinuxArm PI1
- [x] LinuxArm PI2

### CODE REVIEW

**Comment by creationix** [comment]
+1  I can test on my two PIs on Monday when I'm back in my office.

**Comment by rphillips** [comment]
I'm building today on my 1st gen pi... if you could try the 2nd gen that would be great.

**Comment by creationix** [comment]
I tested before the arm tweaks and it worked fine on armv7.

I ran both luvi's unit tests and luvit's unit tests.

**Comment by rphillips** [comment]
There is a consistent 3x performance increase with SSL operations on all the platforms. Less CPU usage as well.

**Comment by creationix** [comment]
+1 all tests pass on my pi.

**Pull request merged**
