### PR TITLE
CMake: Make usage of LUA_PATH in LuaJITAddExecutable depend on it being set

### LINKED ISSUE #242: Build failure with custom LuaJIT (OpenResty fork)
I'm trying to build luvi with a custom LuaJIT, which is the latest release build from the OpenResty fork. This produces the following build error:

```
luajit: unknown luaJIT command or jit.* modules not installed
luajitluajit: unknown luaJIT command or jit.* modules not installed
: unknown luaJIT command or jit.* modules not installed
make[2]: *** [jitted_tmp/src/lua/luvibundle.lua_luvi_generated.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [jitted_tmp/deps/lpeg/re.lua_luvi_generated.o] Error 1
make[2]: *** [jitted_tmp/src/lua/init.lua_luvi_generated.o] Error 1
luajit: unknown luaJIT command or jit.* modules not installed
make[2]: *** [jitted_tmp/src/lua/luvipath.lua_luvi_generated.o] Error 1
make[1]: *** [CMakeFiles/luvi.dir/all] Error 2
make: *** [all] Error 2
```

LuaJIT was built using the standard `make amalg`, so I'm not sure why I'm getting this error. Setting `LUA_PATH` to LuaJIT's `jit` directory as explained in https://github.com/luvit/luvi/commit/a9dc8dae2eb69d4a754a0cf5c08622d70f6b7067 didn't help. Assistance would be appreciated.

Complete build logs: https://gist.github.com/carlocab/2a6c25344be31127f61635d8978b3720

These were generated while attempting a build in Homebrew, but I can reproduce this without Homebrew using just a `make tiny` with the appropriate environment variables for set to enable building with a shared libluv. (I'm actually doing this to assist with Homebrew packaging of luvit. The latest luvi release doesn't build on Apple Silicon.)

### PR DESCRIPTION
**Pull request by squeek502**
Should fix #242

Let me know if this'll work for you @carlocab

### CODE REVIEW

**Comment by carlocab** [comment]
I believe this should work, but let me test it out later.

One thing I'm confused about: the CMake variable `LUA_PATH` is populated by the environment variable `LUA_PATH`. `luajit` should already be reading `LUA_PATH` from the environment and using that value when it's set, so it seems redundant to me to have to call `luajit` with `LUA_PATH=...`.

What am I missing here?

**Comment by squeek502** [comment]
I'm also unclear on that, but wanted to leave it alone just in case. Here's where it was added: https://github.com/luvit/luvi/pull/122

**Comment by zhaozg** [comment]
I have not ideas about this. Maybe found we need find  more direct way.

**Review by zhaozg — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks @squeek502!

**Comment by zhaozg** [comment]
I found the similarly problem, when I do coveralls test lua-openssl. [here]https://github.com/zhaozg/lua-openssl/runs/4824775420?check_suite_focus=true#step:5:599

This maybe a bug in ubuntu with `apt install luajit libluajit-5.1-dev`, https://github.com/zhaozg/lua-openssl/actions/runs/1700632752/workflow#L19

After build luajit from git source, this issue disappeared.

**Pull request merged**
